### ISSUE TITLE
Unable to find image 'adi:sone' locally

### ISSUE THREAD

**Issue by chenfeng15a** [vardhah/ConstraintBOUUVHullDesign#1]
Dear Vardhah: 
         After I download two docker container pre-installed with dependencies along with CAD and CFD software and install GpOPt, when I run:   

> python main_bo.py

         bug occurs:

> Running freecad in Docker 
Unable to find image 'adi:sone' locally
docker: Error response from daemon: pull access denied for adi, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
*** ALL DONE -- ALL DONE ***
*Copied directory from ./cad_sim/stl_repo to destination: ./cfd_sim/stl_cfd
Deleted files from location: ./cad_sim/stl_repo
prev is /home/cf/ConstraintBOUUVHullDesign
func path is: /home/cf/ConstraintBOUUVHullDesign/cfd_sim
file exist?: 1
Loaded files
Traceback (most recent call last):
  File "main_bo.py", line 161, in <module>
    run_bo(run[i],aqu2,seeds[i])
  File "main_bo.py", line 143, in run_bo
    myBopt2D.run_optimization(batch,verbosity=True)
  File "/home/cf/GPyOpt/GPyOpt/core/bo.py", line 156, in run_optimization
    self.evaluate_objective()
  File "/home/cf/GPyOpt/GPyOpt/core/bo.py", line 202, in evaluate_objective
    self.Y_new, cost_new = self.objective.evaluate(self.suggested_sample)
  File "/home/cf/GPyOpt/GPyOpt/core/task/objective.py", line 50, in evaluate
    f_evals, cost_evals = self._eval_func(x)
  File "/home/cf/GPyOpt/GPyOpt/core/task/objective.py", line 74, in _eval_func
    rlt = self.func(np.atleast_2d(x[i]))
  File "main_bo.py", line 88, in run_cad_cfd
    result = main_run()
  File "/home/cf/ConstraintBOUUVHullDesign/cfd_sim/run_dexof.py", line 115, in main_run
    Fd_found,vel= run_dex(mesh)
TypeError: cannot unpack non-iterable NoneType object

Asking for your help. Thanks a lot!

**Comment by vardhah** [comment]
Please look at the new read me file for the updated docker image you need to download. It should work now. You should be installing free cad docker from here: https://hub.docker.com/r/vardhah/freecad/tags 
once installed please check the installed docker image: it should show container vardhah/freecad with tag "019".  
Also, please pull this repo for updated code.
